create table if not exists public.entries (
  entry_index text primary key,
  bigsmiles text not null,
  svg text not null,
  annotations jsonb not null default '[]'::jsonb,
  checked boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  entry_index text not null references public.entries(entry_index) on delete cascade,
  reviewer_name text not null,
  reviewer_email text null,
  created_at timestamptz not null default now(),
  text text not null default '',
  image_url text null
);

create index if not exists comments_entry_index_created_at_idx
  on public.comments(entry_index, created_at);

create or replace function public.set_entries_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists entries_set_updated_at on public.entries;
create trigger entries_set_updated_at
before update on public.entries
for each row execute function public.set_entries_updated_at();

insert into storage.buckets (id, name, public)
values ('validation-comment-images', 'validation-comment-images', true)
on conflict (id) do update set public = excluded.public;
